// <auto-generated />
namespace FengZhen.Restaurant.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FoodsPhoto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FoodsPhoto));
        
        string IMigrationMetadata.Id
        {
            get { return "202004130215020_FoodsPhoto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
